gorod/billboards/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, include, url

from views import BillboardDetailView, BillboardListView


urlpatterns = patterns('',
    url(r'^$', BillboardListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BillboardDetailView.as_view(), name='detail'),
)

gorod/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^', include('gorod.billboards.urls', namespace="billboards")),
)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),
    )

gorod/billboards/models.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
import os.path
import uuid
import urllib2 as url
from django.db import models
from django.core.urlresolvers import reverse


from django.conf import settings
import json


def dir_for_billboard(instance, filename):
        ext = filename.split('.')[-1]
        filename = '%s.%s'%(uuid.uuid4(), ext)
        return os.path.join('billboards', str(instance.billboard.pk), filename)


class City(models.Model):
    name = models.CharField(u'Название', max_length=50)

    class Meta:
        verbose_name = u'Город'
        verbose_name_plural = u'Города'

    def __unicode__(self):
        return self.name


class Format(models.Model):
    name = models.CharField(u'Обозначение', max_length=30)

    class Meta:
        verbose_name = u'Формат'
        verbose_name_plural = u'Форматы'

    def __unicode__(self):
        return self.name


class View(models.Model):
    name = models.CharField(u'Обозначение', max_length=30)

    class Meta:
        verbose_name = u'Вид'
        verbose_name_plural = u'Виды'

    def __unicode__(self):
        return self.name


class Billboard(models.Model):
    city = models.ForeignKey(City, verbose_name=u'Город')
    format = models.ForeignKey(Format, verbose_name=u'Формат')
    view = models.ForeignKey(View, verbose_name=u'Вид')
    address = models.CharField(u'Адрес', max_length=50)
    sides = models.IntegerField(u'Сторон', default=1, choices=((1, '1'), (2, '2')))
    light = models.BooleanField(u'Свет', default=False)
    price = models.DecimalField(u'Цена', max_digits=8, decimal_places=2)
    lat = models.FloatField(default=0, blank=True, editable=False)
    long = models.FloatField(default=0, blank=True, editable=False)

    class Meta:
        verbose_name = u'Рекламное место'
        verbose_name_plural = u'Рекламные места'

    def get_absolute_url(self):
        return reverse("billboards:detail", kwargs={'pk':self.pk})

    def save(self, **kwargs):
        self.long, self.lat = get_coordinate(self.city, self.address)
        super(Billboard, self).save( **kwargs)
class Image(models.Model):
    billboard = models.ForeignKey(Billboard, verbose_name=u'Рекламный щит', related_name='images')
    image = models.ImageField(u'Изображение', upload_to=dir_for_billboard, max_length=255)

    class Meta:
        verbose_name = u'Изображение'
        verbose_name_plural = u'Изображения'


def get_coordinate(city, address):
    geocode = city.name + ',+' + address.replace(' ', '+')
    request = settings.MAPS_GEOCODER_JSON_URL + u'&geocode=' + geocode
    try:
        response = url.urlopen(request.encode('utf-8')).read()
        response = json.loads(response)
        pos = response['response']\
                      ['GeoObjectCollection']\
                      ['featureMember'][0]\
                      ['GeoObject']\
                      ['Point']\
                      ['pos'].split()

        return pos
    except:
        return (None, None)

gorod/billboards/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import ListView, DetailView
from django.db.models import Q
from .models import Billboard


class BillboardListView(ListView):
    def get_queryset(self):
        boards = Billboard.objects.all()
        q = self.request.GET.get('q', None)
        if q:
            boards = boards.filter(Q(city__name__icontains=q)|
                                    Q(format__name__icontains=q)|
                                    Q(view__name__icontains=q)|
                                    Q(address__icontains=q)|
                                    Q(price__icontains=q))
        return boards


class BillboardDetailView(DetailView):
    model = Billboard

gorod/templates/base.html
{% load sekizai_tags flatpages %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% block description %}Рекламные плакаты в Кирове{% endblock %}">
        <link rel="shortcut icon" href="">

        <title>{% block title %}Рекламные плакаты в Кирове{% endblock %}</title>

        {% addtoblock "css" %}
        <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
        {% endaddtoblock %}

        {% addtoblock "js" %}
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="{{ STATIC_URL }}/js/bootstrap.min.js"></script>
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        {% endaddtoblock %}

        {% render_block "css" %}
        {% render_block "js" %}
    </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Главная</a>
            <a class="navbar-brand" href="/pages/about/">О компании</a>
            <a class="navbar-brand" href="/pages/price/">Цены</a>
            <span class="contacts">Сайт продается, тел: 8-909-140-73-62</span>
            
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form" action="{% url "billboards:index" %}" method="get">
            <div class="form-group">
              <input type="text" placeholder="" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-success">Найти</button>
          </form>
        </div>
      </div>
    </div>

    <div class="jumbotron">
        {% block page_description %}
            <div class="container">
                {% get_flatpages '/snippet/' as snippet %}
                {{ snippet.0.content|safe }}
            </div>
        {% endblock %}
    </div>

    <div class="container">
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>

        <hr>

        <footer>
            <p>
                <a class="admin" href="{% url "admin:index" %}">Войти</a>
            </p>
        </footer>
    </div> <!-- /container -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter23740174 = new Ya.Metrika({id:23740174,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/23740174" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

  </body>
</html>

gorod/templates/billboards/billboard_detail.html
{% extends "base.html" %}

{% load sekizai_tags humanize thumbnail %}

{% block page_description %}
    <div class="container">
    <table id="billboards" class="table table-bordered billboards">
        <thead>
            <tr class="success">
                <th>№</th>
                <th>Город</th>
                <th>Формат</th>
                <th>Вид</th>
                <th>Адрес</th>
                <th>Сторон</th>
                <th>Свет</th>
                <th>Стоимость</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ billboard.pk }}</td>
                <td>{{ billboard.city }}</td>
                <td>{{ billboard.format }}</td>
                <td>{{ billboard.view }}</td>
                <td>{{ billboard.address }}</td>
                <td>{{ billboard.sides }}</td>
                <td>
                    {% if billboard.light %}
                        <span class="glyphicon glyphicon-ok-circle"></span>
                    {% else %}
                        <span class="glyphicon glyphicon-ban-circle"></span>
                    {% endif %}
                </td>
                <td>{{ billboard.price|intcomma }}</td>
            </tr>
        </tbody>
      </table>
    </div>
{% endblock %}

{% block content %}
    {% addtoblock "js" %}
        <script src="{{ STATIC_URL }}/fotorama/fotorama.js"></script>
        <script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
    {% endaddtoblock %}
    {% addtoblock "css" %}
        <link href="{{ STATIC_URL }}/fotorama/fotorama.css" rel="stylesheet">
    {% endaddtoblock %}

    <div class="fotorama" data-height="500" data-width="100%" data-nav="thumbs" data-thumbwidth="90">
    {% for image in billboard.images.all %}
        {% thumbnail image.image "90" as img %}
            {% thumbnail image.image "980" as big_img %}
                <a href="{{ big_img.url }}"><img src="{{ img.url }}"></a>
            {% endthumbnail %}
        {% endthumbnail %}
    {% endfor %}
    </div>

    <div id="map" class="map" style="width: 100%; height: 400px">
    </div>

    <script type="text/javascript">
        ymaps.ready(init);
        var myMap;

        function init(){
            myMap = new ymaps.Map ("map", {
                center: [{{ billboard.lat|stringformat:"f" }}, {{ billboard.long|stringformat:"f" }}],
                zoom: 17
            });
            myMap.controls.add(
                        new ymaps.control.ZoomControl()
                    );

            myPlacemark = new ymaps.Placemark([{{ billboard.lat|stringformat:"f" }}, {{ billboard.long|stringformat:"f" }}], {
                content: '{{ billboard.city }}, {{ billboard.address }}',
                balloonContent: '{{ billboard.city }}, {{ billboard.address }}'
            });

            myMap.geoObjects.add(myPlacemark);
        }
    </script>
{% endblock %}

gorod/templates/billboards/billboard_list.html
{% extends "base.html" %}

{% load sekizai_tags humanize %}



{% block content %}
    {% addtoblock "js" %}
        <script src="{{ STATIC_URL }}/js/jquery.tablesorter.min.js"></script>
        <script>
            $(document).ready(function() {
                $("#billboards").tablesorter();
            });
        </script>
    {% endaddtoblock %}
    <table id="billboards" class="table table-bordered billboards">
        <thead>
            <tr class="success">
                <th>№ <span class="glyphicon glyphicon-sort "></span></th>
                <th>Город <span class="glyphicon glyphicon-sort"></span></th>
                <th>Формат <span class="glyphicon glyphicon-sort"></span></th>
                <th>Вид <span class="glyphicon glyphicon-sort"></span></th>
                <th>Адрес <span class="glyphicon glyphicon-sort"></span></th>
                <th>Сторон <span class="glyphicon glyphicon-sort"></span></th>
                <th>Свет <span class="glyphicon glyphicon-sort"></span></th>
                <th>Стоимость <span class="glyphicon glyphicon-sort"></span></th>
                <th>Ссылка</th>
            </tr>
        </thead>
        <tbody>
            {% for board in billboard_list %}
            <tr {% if forloop.counter|divisibleby:"2" %}class="active"{% endif %}>
                <td>{{ board.pk }}</td>
                <td>{{ board.city }}</td>
                <td>{{ board.format }}</td>
                <td>{{ board.view }}</td>
                <td>{{ board.address }}</td>
                <td>{{ board.sides }}</td>
                <td>
                    {% if board.light %}
                        <span class="glyphicon glyphicon-ok-circle"></span>
                    {% else %}
                        <span class="glyphicon glyphicon-ban-circle"></span>
                    {% endif %}
                </td>
                <td>{{ board.price|intcomma }}</td>
                <td><a href="{{ board.get_absolute_url }}">Фото</a></td>
            </tr>
            {% endfor %}
        </tbody>
      </table>

{% endblock %}